// Generated by the protocol buffer compiler.  DO NOT EDIT!

package sizzle.types;

public final class Querylog {
  private Querylog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class QueryLogProto extends
      com.google.protobuf.GeneratedMessage {
    // Use QueryLogProto.newBuilder() to construct.
    private QueryLogProto() {}
    
    private static final QueryLogProto defaultInstance = new QueryLogProto();
    public static QueryLogProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public QueryLogProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.Querylog.internal_static_sizzle_types_QueryLogProto_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.Querylog.internal_static_sizzle_types_QueryLogProto_fieldAccessorTable;
    }
    
    // required string ip = 1;
    private boolean hasIp;
    private java.lang.String ip_ = "";
    public boolean hasIp() { return hasIp; }
    public java.lang.String getIp() { return ip_; }
    
    // required int64 time_usec = 2;
    private boolean hasTimeUsec;
    private long timeUsec_ = 0L;
    public boolean hasTimeUsec() { return hasTimeUsec; }
    public long getTimeUsec() { return timeUsec_; }
    
    public static sizzle.types.Querylog.QueryLogProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Querylog.QueryLogProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Querylog.QueryLogProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Querylog.QueryLogProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Querylog.QueryLogProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Querylog.QueryLogProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Querylog.QueryLogProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Querylog.QueryLogProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(sizzle.types.Querylog.QueryLogProto prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using sizzle.types.Querylog.QueryLogProto.newBuilder()
      private Builder() {}
      
      sizzle.types.Querylog.QueryLogProto result = new sizzle.types.Querylog.QueryLogProto();
      
      @Override
      protected sizzle.types.Querylog.QueryLogProto internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new sizzle.types.Querylog.QueryLogProto();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.Querylog.QueryLogProto.getDescriptor();
      }
      
      public sizzle.types.Querylog.QueryLogProto getDefaultInstanceForType() {
        return sizzle.types.Querylog.QueryLogProto.getDefaultInstance();
      }
      
      public sizzle.types.Querylog.QueryLogProto build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private sizzle.types.Querylog.QueryLogProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public sizzle.types.Querylog.QueryLogProto buildPartial() {
        sizzle.types.Querylog.QueryLogProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string ip = 1;
      public boolean hasIp() {
        return result.hasIp();
      }
      public java.lang.String getIp() {
        return result.getIp();
      }
      public Builder setIp(java.lang.String value) {
        result.hasIp = true;
        result.ip_ = value;
        return this;
      }
      public Builder clearIp() {
        result.hasIp = false;
        result.ip_ = "";
        return this;
      }
      
      // required int64 time_usec = 2;
      public boolean hasTimeUsec() {
        return result.hasTimeUsec();
      }
      public long getTimeUsec() {
        return result.getTimeUsec();
      }
      public Builder setTimeUsec(long value) {
        result.hasTimeUsec = true;
        result.timeUsec_ = value;
        return this;
      }
      public Builder clearTimeUsec() {
        result.hasTimeUsec = false;
        result.timeUsec_ = 0L;
        return this;
      }
    }
    
    static {
      sizzle.types.Querylog.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_QueryLogProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_QueryLogProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\016querylog.proto\022\014sizzle.types\".\n\rQueryL" +
      "ogProto\022\n\n\002ip\030\001 \002(\t\022\021\n\ttime_usec\030\002 \002(\003";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sizzle_types_QueryLogProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sizzle_types_QueryLogProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_QueryLogProto_descriptor,
              new java.lang.String[] { "Ip", "TimeUsec", },
              sizzle.types.Querylog.QueryLogProto.class,
              sizzle.types.Querylog.QueryLogProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
