// Generated by the protocol buffer compiler.  DO NOT EDIT!

package sizzle.types;

public final class SizzleDocument {
  private SizzleDocument() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Document extends
      com.google.protobuf.GeneratedMessage {
    // Use Document.newBuilder() to construct.
    private Document() {}
    
    private static final Document defaultInstance = new Document();
    public static Document getDefaultInstance() {
      return defaultInstance;
    }
    
    public Document getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.SizzleDocument.internal_static_sizzle_types_Document_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.SizzleDocument.internal_static_sizzle_types_Document_fieldAccessorTable;
    }
    
    // required string url = 1;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public boolean hasUrl() { return hasUrl; }
    public java.lang.String getUrl() { return url_; }
    
    // required int64 pagerank = 2;
    private boolean hasPagerank;
    private long pagerank_ = 0L;
    public boolean hasPagerank() { return hasPagerank; }
    public long getPagerank() { return pagerank_; }
    
    public static sizzle.types.SizzleDocument.Document parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.SizzleDocument.Document parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleDocument.Document parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.SizzleDocument.Document parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleDocument.Document parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.SizzleDocument.Document parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleDocument.Document parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.SizzleDocument.Document parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(sizzle.types.SizzleDocument.Document prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using sizzle.types.SizzleDocument.Document.newBuilder()
      private Builder() {}
      
      sizzle.types.SizzleDocument.Document result = new sizzle.types.SizzleDocument.Document();
      
      @Override
      protected sizzle.types.SizzleDocument.Document internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new sizzle.types.SizzleDocument.Document();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.SizzleDocument.Document.getDescriptor();
      }
      
      public sizzle.types.SizzleDocument.Document getDefaultInstanceForType() {
        return sizzle.types.SizzleDocument.Document.getDefaultInstance();
      }
      
      public sizzle.types.SizzleDocument.Document build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private sizzle.types.SizzleDocument.Document buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public sizzle.types.SizzleDocument.Document buildPartial() {
        sizzle.types.SizzleDocument.Document returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string url = 1;
      public boolean hasUrl() {
        return result.hasUrl();
      }
      public java.lang.String getUrl() {
        return result.getUrl();
      }
      public Builder setUrl(java.lang.String value) {
        result.hasUrl = true;
        result.url_ = value;
        return this;
      }
      public Builder clearUrl() {
        result.hasUrl = false;
        result.url_ = "";
        return this;
      }
      
      // required int64 pagerank = 2;
      public boolean hasPagerank() {
        return result.hasPagerank();
      }
      public long getPagerank() {
        return result.getPagerank();
      }
      public Builder setPagerank(long value) {
        result.hasPagerank = true;
        result.pagerank_ = value;
        return this;
      }
      public Builder clearPagerank() {
        result.hasPagerank = false;
        result.pagerank_ = 0L;
        return this;
      }
    }
    
    static {
      sizzle.types.SizzleDocument.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_Document_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_Document_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\025sizzle_document.proto\022\014sizzle.types\")\n" +
      "\010Document\022\013\n\003url\030\001 \002(\t\022\020\n\010pagerank\030\002 \002(\003";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sizzle_types_Document_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sizzle_types_Document_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_Document_descriptor,
              new java.lang.String[] { "Url", "Pagerank", },
              sizzle.types.SizzleDocument.Document.class,
              sizzle.types.SizzleDocument.Document.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
