// Generated by the protocol buffer compiler.  DO NOT EDIT!

package sizzle.types;

public final class SizzleLocation {
  private SizzleLocation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Location extends
      com.google.protobuf.GeneratedMessage {
    // Use Location.newBuilder() to construct.
    private Location() {}
    
    private static final Location defaultInstance = new Location();
    public static Location getDefaultInstance() {
      return defaultInstance;
    }
    
    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.SizzleLocation.internal_static_sizzle_types_Location_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.SizzleLocation.internal_static_sizzle_types_Location_fieldAccessorTable;
    }
    
    // required double lat = 1;
    private boolean hasLat;
    private double lat_ = 0D;
    public boolean hasLat() { return hasLat; }
    public double getLat() { return lat_; }
    
    // required double lon = 2;
    private boolean hasLon;
    private double lon_ = 0D;
    public boolean hasLon() { return hasLon; }
    public double getLon() { return lon_; }
    
    public static sizzle.types.SizzleLocation.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(sizzle.types.SizzleLocation.Location prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using sizzle.types.SizzleLocation.Location.newBuilder()
      private Builder() {}
      
      sizzle.types.SizzleLocation.Location result = new sizzle.types.SizzleLocation.Location();
      
      @Override
      protected sizzle.types.SizzleLocation.Location internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new sizzle.types.SizzleLocation.Location();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.SizzleLocation.Location.getDescriptor();
      }
      
      public sizzle.types.SizzleLocation.Location getDefaultInstanceForType() {
        return sizzle.types.SizzleLocation.Location.getDefaultInstance();
      }
      
      public sizzle.types.SizzleLocation.Location build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private sizzle.types.SizzleLocation.Location buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public sizzle.types.SizzleLocation.Location buildPartial() {
        sizzle.types.SizzleLocation.Location returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required double lat = 1;
      public boolean hasLat() {
        return result.hasLat();
      }
      public double getLat() {
        return result.getLat();
      }
      public Builder setLat(double value) {
        result.hasLat = true;
        result.lat_ = value;
        return this;
      }
      public Builder clearLat() {
        result.hasLat = false;
        result.lat_ = 0D;
        return this;
      }
      
      // required double lon = 2;
      public boolean hasLon() {
        return result.hasLon();
      }
      public double getLon() {
        return result.getLon();
      }
      public Builder setLon(double value) {
        result.hasLon = true;
        result.lon_ = value;
        return this;
      }
      public Builder clearLon() {
        result.hasLon = false;
        result.lon_ = 0D;
        return this;
      }
    }
    
    static {
      sizzle.types.SizzleLocation.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_Location_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\025sizzle_location.proto\022\014sizzle.types\"$\n" +
      "\010Location\022\013\n\003lat\030\001 \002(\001\022\013\n\003lon\030\002 \002(\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sizzle_types_Location_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sizzle_types_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_Location_descriptor,
              new java.lang.String[] { "Lat", "Lon", },
              sizzle.types.SizzleLocation.Location.class,
              sizzle.types.SizzleLocation.Location.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
