// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sizzle_location.proto

package sizzle.types;

public final class SizzleLocation {
  private SizzleLocation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required double lat = 1;
    boolean hasLat();
    double getLat();
    
    // required double lon = 2;
    boolean hasLon();
    double getLon();
  }
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(Builder builder) {
      super(builder);
    }
    private Location(boolean noInit) {}
    
    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }
    
    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.SizzleLocation.internal_static_sizzle_types_Location_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.SizzleLocation.internal_static_sizzle_types_Location_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required double lat = 1;
    public static final int LAT_FIELD_NUMBER = 1;
    private double lat_;
    public boolean hasLat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getLat() {
      return lat_;
    }
    
    // required double lon = 2;
    public static final int LON_FIELD_NUMBER = 2;
    private double lon_;
    public boolean hasLon() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getLon() {
      return lon_;
    }
    
    private void initFields() {
      lat_ = 0D;
      lon_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, lon_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lon_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sizzle.types.SizzleLocation.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.SizzleLocation.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.SizzleLocation.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sizzle.types.SizzleLocation.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sizzle.types.SizzleLocation.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sizzle.types.SizzleLocation.internal_static_sizzle_types_Location_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sizzle.types.SizzleLocation.internal_static_sizzle_types_Location_fieldAccessorTable;
      }
      
      // Construct using sizzle.types.SizzleLocation.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.SizzleLocation.Location.getDescriptor();
      }
      
      public sizzle.types.SizzleLocation.Location getDefaultInstanceForType() {
        return sizzle.types.SizzleLocation.Location.getDefaultInstance();
      }
      
      public sizzle.types.SizzleLocation.Location build() {
        sizzle.types.SizzleLocation.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sizzle.types.SizzleLocation.Location buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sizzle.types.SizzleLocation.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sizzle.types.SizzleLocation.Location buildPartial() {
        sizzle.types.SizzleLocation.Location result = new sizzle.types.SizzleLocation.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lon_ = lon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sizzle.types.SizzleLocation.Location) {
          return mergeFrom((sizzle.types.SizzleLocation.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sizzle.types.SizzleLocation.Location other) {
        if (other == sizzle.types.SizzleLocation.Location.getDefaultInstance()) return this;
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLat()) {
          
          return false;
        }
        if (!hasLon()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              lat_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lon_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required double lat = 1;
      private double lat_ ;
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getLat() {
        return lat_;
      }
      public Builder setLat(double value) {
        bitField0_ |= 0x00000001;
        lat_ = value;
        onChanged();
        return this;
      }
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0D;
        onChanged();
        return this;
      }
      
      // required double lon = 2;
      private double lon_ ;
      public boolean hasLon() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getLon() {
        return lon_;
      }
      public Builder setLon(double value) {
        bitField0_ |= 0x00000002;
        lon_ = value;
        onChanged();
        return this;
      }
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lon_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sizzle.types.Location)
    }
    
    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sizzle.types.Location)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_Location_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025sizzle_location.proto\022\014sizzle.types\"$\n" +
      "\010Location\022\013\n\003lat\030\001 \002(\001\022\013\n\003lon\030\002 \002(\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sizzle_types_Location_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sizzle_types_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_Location_descriptor,
              new java.lang.String[] { "Lat", "Lon", },
              sizzle.types.SizzleLocation.Location.class,
              sizzle.types.SizzleLocation.Location.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
